# Generated by Django 4.0.3 on 2022-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
