# Generated by Django 4.0.3 on 2023-07-02 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_remove_bug_likes_bug_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='likes',
        ),
        migrations.AddField(
            model_name='bug',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
