# Generated by Django 4.0.3 on 2023-07-02 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_remove_bug_likes_bug_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='likes',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='respond_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
