# Generated by Django 4.0.3 on 2022-05-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0004_game_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
