# Generated by Django 4.0.3 on 2022-05-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0008_score_extra_alter_score_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='extra',
        ),
        migrations.AddField(
            model_name='game',
            name='scoring',
            field=models.CharField(blank=True, choices=[('timer', 'Timer'), ('points', 'Points')], max_length=20),
        ),
    ]
