# Generated by Django 4.0.3 on 2022-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0010_alter_game_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='context',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
