# Generated by Django 4.0.3 on 2022-05-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0012_alter_game_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='context',
        ),
    ]
